# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class T < Formula
  desc "Display time in various timezones using IATA airport codes"
  homepage "https://github.com/cv/t"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cv/t/releases/download/v0.2.0/t_Darwin_x86_64.tar.gz"
      sha256 "eae9574040e0e4baff9b447519190808fb615ed5376b296a01cd5de6b253dc71"

      def install
        bin.install "t"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cv/t/releases/download/v0.2.0/t_Darwin_arm64.tar.gz"
      sha256 "cc507df3337ebdf6591c7b88989977f6ddb0cf223daef56c25c298732463c99c"

      def install
        bin.install "t"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cv/t/releases/download/v0.2.0/t_Linux_x86_64.tar.gz"
      sha256 "8b8c2d0fdf92210bcb3357983853c41e091ee865fb420118bdb97ec763db2776"
      def install
        bin.install "t"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cv/t/releases/download/v0.2.0/t_Linux_arm64.tar.gz"
      sha256 "6289dff32a7a130b6f49ac75f3ae2967361468ca6fa5a82a98d74d9f472f4557"
      def install
        bin.install "t"
      end
    end
  end

  test do
    system "#{bin}/t", "--version"
  end
end
