# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class T < Formula
  desc "Display time in various timezones using IATA airport codes"
  homepage "https://github.com/cv/t"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cv/t/releases/download/v0.1.0/t_Darwin_x86_64.tar.gz"
      sha256 "dbce2f63f922bb19b0ae9e3eac825cddb8f0b309fc49ab9aae37f4a75f8aacf8"

      def install
        bin.install "t"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cv/t/releases/download/v0.1.0/t_Darwin_arm64.tar.gz"
      sha256 "2c14ead3cbbd281039bf30fcd8e1519f7dfab06cba7d294d9b3733e1ab2bb6eb"

      def install
        bin.install "t"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cv/t/releases/download/v0.1.0/t_Linux_x86_64.tar.gz"
      sha256 "c99d9971f0b47c719271f3ad54577c9c411b11ff18300a322783d547ad572b48"
      def install
        bin.install "t"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cv/t/releases/download/v0.1.0/t_Linux_arm64.tar.gz"
      sha256 "7eb5dfc2fcc54c93103a3da2e8789f2387ff536cb92b7865da3758103a9b746c"
      def install
        bin.install "t"
      end
    end
  end

  test do
    system "#{bin}/t", "--version"
  end
end
